name: dribbly
description: A Flutter project made with Firebase that help you for your next Yoga sessions.

publish_to: 'none' 



environment:
  sdk: ">=2.12.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  provider: ^5.0.0
  form_field_validator: ^1.1.0
  audioplayers: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.0.0	
  flutter_launcher_icons: ^0.9.0

flutter_native_splash:
  background_image: "assets/background.png"
  image: "assets/splashIcon.png"

flutter_icons:
  image_path: "assets/appIcon.png"
  android: true
  ios: true


flutter:
    
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/bottom/
    - assets/illustrations/
